application: netzen-hrd
version: 7
runtime: python27
api_version: 1
default_expiration: 365d
threadsafe: false

builtins:
- appstats: on

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /static/(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /static/(.*\.webm)
  mime_type: video/webm
  static_files: static/\1
  upload: static/(.*\.webm)

- url: /static/(.*\.webapp)
  mime_type: application/x-web-app-manifest+json
  static_files: static/\1
  upload: static/(.*\.webapp)

- url: /static/(.*\.mp4)
  mime_type: video/mp4
  static_files: static/\1
  upload: static/(.*\.mp4)

- url: /static
  static_dir: static

#- url: /admin/.*
#  script: urls.py
#  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
